name: Deploy to AWS EC2 Automation

on:
  push:
    branches:
      - development
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/development' && 'dev' || github.ref == 'refs/heads/staging' && 'staging' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This fetches all history for all branches and tags.

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # so it exits immediately if a command exits with a non-zero status
            sudo usermod -aG docker $USER
            newgrp docker

            if [ ! -d "/home/ubuntu/cyflare_one_dummy_org_data_generator" ]; then
              git clone -b ${{github.ref_name}} git@github.com-${{github.event.repository.name}}:${{github.repository}}.git /home/ubuntu/cyflare_one_dummy_org_data_generator
            fi

            cd /home/ubuntu/cyflare_one_dummy_org_data_generator
            git pull origin ${{github.ref_name}}

            echo LOG_LEVEL='${{ vars.LOG_LEVEL }}' > .env
            echo POSTGRESQL_HOST='${{ secrets.POSTGRESQL_HOST }}' >> .env
            echo POSTGRESQL_USER='${{ secrets.POSTGRESQL_USER }}' >> .env
            echo POSTGRESQL_PASSWORD='${{ secrets.POSTGRESQL_PASSWORD }}' >> .env
            echo POSTGRESQL_DATABASE='${{ vars.POSTGRESQL_DATABASE }}' >> .env
            echo POSTGRESQL_PORT='${{ vars.POSTGRESQL_PORT }}' >> .env

            docker build -t cyflare_one_dummy_org_data_generator -f Dockerfile .

             # Check and add the process cron job - runs once a day at 6am
            (crontab -l | grep -v "cyflare_one_dummy_org_data_generator" ; echo "0 6 * * * /usr/bin/docker run --log-driver=syslog --rm --name cyflare_one_dummy_org_data_generator cyflare_one_dummy_org_data_generator") | crontab -
